import { appState } from '../../core/state.js';

let segmenterInstance = null;
let isInitializingSegmenter = false;

async function ensureMediaPipeLoaded() {
  if (typeof window.SelfieSegmentation !== 'undefined') return true;
  return new Promise((resolve, reject) => {
    const existing = document.querySelector('script[src*="selfie_segmentation"]');
    if (existing) {
      existing.addEventListener('load', () => resolve(true));
      existing.addEventListener('error', () => reject(new Error('Failed to load MediaPipe script')));
      return;
    }
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/selfie_segmentation.js';
    script.crossOrigin = 'anonymous';
    script.onload = () => resolve(true);
    script.onerror = () => reject(new Error('Failed to load MediaPipe script from CDN'));
    document.head.appendChild(script);
  });
}

export async function getSegmenter() {
  if (segmenterInstance) return segmenterInstance;
  if (isInitializingSegmenter) {
    let attempts = 0;
    while (isInitializingSegmenter && attempts < 40) {
      await new Promise((r) => setTimeout(r, 100));
      attempts++;
    }
    if (segmenterInstance) return segmenterInstance;
  }
  isInitializingSegmenter = true;
  try {
    await ensureMediaPipeLoaded();
    if (typeof window.SelfieSegmentation === 'undefined') throw new Error('SelfieSegmentation library could not be loaded');
    const segmenter = new window.SelfieSegmentation({
      locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`
    });
    segmenter.setOptions({ modelSelection: 1 });
    await segmenter.initialize();
    segmenterInstance = segmenter;
    return segmenterInstance;
  } finally {
    isInitializingSegmenter = false;
  }
}

export async function removeBgLocalAi(imageElement, options = {}) {
  const segmenter = await getSegmenter();
  const origW = imageElement.naturalWidth || imageElement.width;
  const origH = imageElement.naturalHeight || imageElement.height;

  const maskResults = await new Promise((resolve, reject) => {
    let timeout = setTimeout(() => reject(new Error('Local AI segmentation timed out')), 25000);
    segmenter.onResults((results) => { clearTimeout(timeout); resolve(results); });
    segmenter.send({ image: imageElement }).catch((err) => { clearTimeout(timeout); reject(err); });
  });
  if (!maskResults?.segmentationMask) throw new Error('No segmentation mask generated by Local AI');

  const canvas = document.createElement('canvas');
  canvas.width = origW; canvas.height = origH;
  const ctx = canvas.getContext('2d', { willReadFrequently: true });
  ctx.drawImage(imageElement, 0, 0, origW, origH);
  const imgData = ctx.getImageData(0, 0, origW, origH);
  const data = imgData.data;

  const maskCanvas = document.createElement('canvas');
  maskCanvas.width = origW; maskCanvas.height = origH;
  const maskCtx = maskCanvas.getContext('2d', { willReadFrequently: true });
  maskCtx.drawImage(maskResults.segmentationMask, 0, 0, origW, origH);
  const maskData = maskCtx.getImageData(0, 0, origW, origH).data;

  const totalPixels = origW * origH;
  for (let i = 0; i < totalPixels; i++) {
    const confidence = maskData[i * 4] / 255;
    if (confidence >= 0.70) {
      data[i * 4 + 3] = 255;
    } else if (confidence <= 0.20) {
      data[i * 4 + 3] = 0;
    } else {
      const t = (confidence - 0.20) / 0.50;
      data[i * 4 + 3] = Math.round(t * t * t * (t * (t * 6 - 15) + 10) * 255);
    }
  }

  ctx.putImageData(imgData, 0, 0);
  const processedImg = new Image();
  await new Promise((resolve, reject) => {
    processedImg.onload = resolve; processedImg.onerror = reject;
    processedImg.src = canvas.toDataURL('image/png');
  });
  return processedImg;
}
